import '../globals.css'
import { ClerkProvider, currentUser } from "@clerk/nextjs"
import Navbar from '@/components/Navbar'
import Bottombar from '@/components/Bottombar'
import Leftbar from '@/components/Leftbar'
import Rightbar from '@/components/Rightbar'


export const metadata = {
  title: 'Threads',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  const user = await currentUser()
  if (!user) {
    console.log("!found")
  }


  return (
    <ClerkProvider>
      <html lang="en">
        <body className=' text-sm'>
          <div className=' h-full'>
            <Navbar />
            <main className=' flex justify-between'>
              <Leftbar user={user?.id} />
              <div className='pl-0 sm:pl-28 md:pl-48 lg:pr-36 pt-12 w-full pb-5'>
                {children}
              </div>
              <div className=' hidden'>
                <Rightbar />
              </div>
            </main>
            <Bottombar user={user?.id} />
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
